### ISSUE TITLE
Add, update and delete Rasa intents

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#74] opened 2023-01-20 07:36 UTC
AS A Trainer
I WANT TO add, update and delete Rasa intents
SO THAT I could manipulate training data and models based on it

> See [temporary list of related API endpoints](https://github.com/buerokratt/Buerokratt-onboarding/issues/8)

### Acceptance Criteria

> List of intents - https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/tree/main/data/nlu

> Sample `YAML` file with intents and their examples - https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/blob/main/data/nlu/common_teenus_ilm_nlu.yml

**Adding new intents**
- [x] New Rasa intents are added by using `intent name` + `_nlu.yaml.tmp` suffix as a file name
- [x] Duplicate intents can not be added
- [ ] When new intents are added to the model, the rules of #76 apply

**Updating existing intents**
- [x] When the intent's name changes, the Rasa YAML file name also changes accordingly

#### When the intent's name changes, intent's new name applies in multiple files

_**When changing `.yml` files**_

- [x] intent's YAML, [see example](https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/blob/main/data/nlu/common_teenus_ilm_nlu.yml)
- [ ] [/data/rules.yml](https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/blob/main/data/rules.yml)
- [x] [/data/stories.yml](https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/blob/main/data/stories.yml)
- [ ] [/domain.yml](https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/blob/main/domain.yml)

_**When changing `.yml.tmp` files**_

- [ ] intent's YAML, [see example](https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/blob/main/data/nlu/common_teenus_ilm_nlu.yml)
- [ ] [/domain.yml](https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/blob/main/domain.yml)

**Deleting existing intents**

- [ ] When intents are deleted via GUI, such intents are moved to a configurable (for example `/deleted`) directory
- [ ] When the intent is defined in [/data/rules.yml](https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/blob/main/data/rules.yml), intent can not be deleted
- [ ] When the intent is defined in [/data/stories.yml](https://koodivaramu.eesti.ee/buerokratt/plug-and-play/rasa-ilmateenused/-/blob/main/data/stories.yml), intent can not be deleted

**Comment by RaulAltmae** [comment] 2023-03-13 14:27
i added endpoint for fetching examples from files.
sample input for `/intents/add` 
```json
{
    "intent": "test_intent"
}
```

**Comment by RaulAltmae** [comment] 2023-03-13 14:27
sample input for `/intents/update` 
```json
{
    "intent": "common_tervitus",
    "new_name": "common_teretus"
}
```

**Comment by RaulAltmae** [comment] 2023-03-13 14:27
sample input for `/intents/delete` 
```json
{
    "intent": "common_tervitus"
}
```

**Comment by turnerrainer** [comment] 2023-03-17 06:45
@RaulAltmae please link this issue with an appropriate pull request.

**Comment by RaulAltmae** [comment] 2023-03-17 13:59
Pull request https://github.com/buerokratt/Training-Module/pull/180

**Comment by Kristjan259** [comment] 2023-07-18 10:38
Work hours include all the onboarding tasks.

**Comment by KasparMinn** [comment] 2023-10-26 14:45
PR: https://github.com/buerokratt/Training-Module/pull/270

This pull request finalizes the add, update, and delete intents functionality in the training module. 

On any one of those processes, the request sent from the front-end remains relatively simple while Ruuter will have to work through a relatively long DSL that makes several different calls between the file system, OpenSearch, and Database, all of which need to remain in the same state to avoid errors. 

To accomplish this, most processes are also checked and validated before happening, which adds to the complexity of the request. This also means that, depending on the server load, requests will usually take between 1 to 5 seconds and front-end is not updated instantly until they are completed, which is why some changes were made in the GUI, particularly the optimization of the page as well as changing the order of things happening on the screen between the start, load, and completion of requests. Additionally, added a small new component, LoadingDialogue, a simpler derivative of the regular Dialogue (no new imports used), which can be used anywhere in the application.

In addition to that, fixed some console inconsistencies and bugs regarding file deletion without changing the processes already working elsewhere in the module.

- Simplified and optimized front-end 
- Added a separate delete-intent script 
- Added a LoadingDialogue component 
- Added OpenSearch checks & calls in DSL files
- Added Database checks & calls in DSL files
- Fixed a bug with empty Intent (without examples)
- Fixed several deletion and file check bugs

**Comment by ffrose** [comment] 2023-11-23 12:50
BUG - 
1. Can't see or open existing intents, can't add new intents.
2. When trying to open right now:  ![image](https://github.com/buerokratt/Training-Module/assets/119657383/c18fd3e9-28db-49ae-a8fe-0ff9a65feb17)
3.  How it should look like:
![image](https://github.com/buerokratt/Training-Module/assets/119657383/dd55339d-1869-4721-8ac0-cbfb6db782ba)

**Comment by turnerrainer** [comment] 2023-11-24 13:22
@ffrose there were major updates today, please see if they helped in this case as well.

**Comment by ffrose** [comment] 2023-11-30 11:28
@turnerrainer still unable to edit, save, add or delete intents. status code 300

**Comment by KasparMinn** [comment] 2023-12-01 09:26
@ffrose Should be fixed now, I'm opening and testing it on dev and see it working.

**Comment by ffrose** [comment] 2023-12-01 17:59
@KasparMinn As of right now, when adding a new topic (creating a new nlu file) the minimum amount for the title is 6 characters, it should be 3.

**Comment by KasparMinn** [comment] 2023-12-11 12:22
Should be fixed as of https://github.com/buerokratt/Training-Module/pull/316

**Comment by ValterAro** [comment] 2023-12-12 09:38
Short summary: when changing the examples in an intent then you need to refresh the page to see the change.
Expected result: after changing the examples you should see the change right away
Real result: after making a change in an example you need to refresh the page or look at another intent and then go back.
How to reproduce: go to https://admin.dev.buerokratt.ee/training/training/intents after logging in and select one of the intents with examples. Then change one of the examples.



![Image](https://github.com/buerokratt/Training-Module/assets/122787093/a7ce9544-1c21-4187-8749-39b48ea3b7f7)

**Comment by turnerrainer** [comment] 2024-01-25 08:17
Same bug as #79

**Comment by ValterAro** [comment] 2024-02-05 11:45
Short summary: When you delete an intent then you need to refresh the page to see the change.
Expected result: After deleting an intent you should see the change immediately.
Real result: You need to refresh the page for the intent to disappear that has been deleted.
How to reproduce: login and go to https://admin.dev.buerokratt.ee/training/training/intents and then add an intent and the delete an intent.
Pic:


![Image](https://github.com/buerokratt/Training-Module/assets/122787093/5e790088-17d8-47c3-a4ef-30aeacabd1aa)

**Comment by ExiRain** [comment] 2024-02-15 08:05
[Pull request ](https://github.com/buerokratt/Training-Module/pull/377)with fixing  refetching data

**Comment by ffrose** [comment] 2024-02-15 10:59
BUG - able to add, update and delete intents, yet if intents include single ' or double " quatation marks, it replaces it with: &amp;amp;#x27;
Not sure about this but when adding multiple intents with previously named symbols, it hides/deletes all the other intents. Can not repeat this everytime. 

![Image](https://github.com/buerokratt/Training-Module/assets/119657383/07cd8bcb-3ad5-4cfd-8c82-c920ecb8a0c5)

**Comment by ExiRain** [comment] 2024-02-21 08:02
[Pull request.](https://github.com/buerokratt/Training-Module/pull/389)
Added support for single quotations for intent examples, entities, responses.
Currently we don't need double quotations support

**Closed** 2024-02-22 14:04 UTC
Labels: sprint 5, sprint 6, sprint 7, sprint 8, sprint 9, sprint 10, sprint 11, sprint 12, sprint 13, sprint 14, sprint 15, sprint 16, sprint 17, sprint 18, sprint 19, sprint 20, sprint 21, sprint 22, sprint 23, sprint 24, sprint 25, sprint 26, sprint 27

**Comment by ffrose** [comment] 2024-02-26 21:58
Works as intended.
