### ISSUE TITLE
[BUG] Links in training module history not opening in new tab

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Training-Module#709] opened 2024-11-21 07:45 UTC
**Bug description:**
When clicking on a link in a chat in /training/history/history, the link is opened in the same tab

**Expected behavior:**
Clicking on a link in /training/history/history opens the link in a new tab like in /chat/history

**Comment by ffrose** [comment] 2024-11-21 13:26
As of right now, when clicking on a link in /training/history/history, it still opens the link in the same tab, not in new.

**Comment by 1AhmedYasser** [comment] 2024-11-21 17:46
@ffrose this is not deployed yet, it was only merged, please move this to to-deploy

**Comment by ffrose** [comment] 2024-11-26 08:12
Works as intended. New tab is being opened when clicking on links.

**Closed by ffrose** 2024-11-26 08:12 UTC
Labels: bug, v2.0.2
